/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.48
 * Generated at: 2025-11-19 21:20:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import culturarte.servicios.cliente.usuario.DtUsuario;
import culturarte.servicios.cliente.imagenes.*;

public final class cabezalComun_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("culturarte.servicios.cliente.imagenes");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("culturarte.servicios.cliente.usuario.DtUsuario");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <div class=\"menu-hamburguesa\">\r\n");
      out.write("        <button class=\"menu-toggle\" id=\"menuToggle\" aria-label=\"Abrir menú\">\r\n");
      out.write("            <span></span>\r\n");
      out.write("            <span></span>\r\n");
      out.write("            <span></span>\r\n");
      out.write("        </button>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"logo\">\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/principal\" style=\"text-decoration: none;\">\r\n");
      out.write("            <img src=\"imagenes/culturarte.png\" alt=\"Logo Culturarte\" style=\"width:150px; height:auto;\">\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"sidebar-menu\" id=\"sidebarMenu\">\r\n");
      out.write("        <div class=\"sidebar-header\">\r\n");
      out.write("            <h3>Menú</h3>\r\n");
      out.write("            <button class=\"sidebar-close\" id=\"sidebarClose\" aria-label=\"Cerrar menú\">&times;</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav class=\"sidebar-nav\">\r\n");
      out.write("            ");

                Boolean esProponente = (Boolean) request.getAttribute("esProponente");
                Boolean esColaborador = (Boolean) request.getAttribute("esColaborador");
                
                if (esProponente != null && esProponente) {
            
      out.write("\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/altaPropuesta\" class=\"sidebar-item\">\r\n");
      out.write("                    <span>📝</span> Nueva Propuesta\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/ejecutarPropuesta\" class=\"sidebar-item\">\r\n");
      out.write("                    <span>▶️</span> Ejecutar Propuestas\r\n");
      out.write("                </a>\r\n");
      out.write("            ");

                }
                
                if (esColaborador != null && esColaborador) {
            
      out.write("\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/recomendacionPropuestas\" class=\"sidebar-item\">\r\n");
      out.write("                    <span>⭐</span> Recomendaciones de Propuestas\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/listarPropuestasParaComentar\" class=\"sidebar-item\">\r\n");
      out.write("                    <span>💬</span> Comentar Propuestas\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/listarColaboracionesConstancia\" class=\"sidebar-item\">\r\n");
      out.write("                    <span>📄</span> Constancias de Pago\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/listarColaboracionesParaPagar\" class=\"sidebar-item\">\r\n");
      out.write("                    <span>💳</span> Pagar Colaboración\r\n");
      out.write("                </a>\r\n");
      out.write("            ");

                }
            
      out.write("\r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/VerRankingDeUsuarios\" class=\"sidebar-item\">\r\n");
      out.write("                <span>🏆</span> Ver Ranking de Usuarios\r\n");
      out.write("            </a>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"sidebar-overlay\" id=\"sidebarOverlay\"></div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"Botones-Menu-Superior\">\r\n");
      out.write("        <a href=\"consultaPropuesta\">Ver Propuestas</a> |\r\n");
      out.write("        <a href=\"consultaPerfilUsuario\">Ver Usuarios</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"search-bar-Menu-Superior\">\r\n");
      out.write("        <form method=\"get\" action=\"");
      out.print( request.getContextPath() );
      out.write("/consultaPropuesta\" style=\"display: flex; gap: 10px; width: 100%;\">\r\n");
      out.write("            <input type=\"text\" name=\"busqueda\" placeholder=\"Buscar por título, lugar o descripción...\"\r\n");
      out.write("                   value=\"");
      out.print( request.getParameter("busqueda") != null ? request.getParameter("busqueda") : "" );
      out.write("\"\r\n");
      out.write("                   style=\"flex: 1; padding: 10px; border: 1px solid #ddd; border-radius: 4px;\">\r\n");
      out.write("            <button type=\"submit\" style=\"padding: 10px 20px; background-color: #333; color: white; border: none; border-radius: 4px; cursor: pointer;\">Buscar</button>\r\n");
      out.write("            ");
 if (request.getParameter("busqueda") != null && !request.getParameter("busqueda").isEmpty()) { 
      out.write("\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/consultaPropuesta\"\r\n");
      out.write("                   style=\"padding: 10px 15px; background-color: #666; color: white; text-decoration: none; border-radius: 4px; display: flex; align-items: center;\">\r\n");
      out.write("                    Limpiar\r\n");
      out.write("                </a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"Botones-Menu-Superior\">\r\n");
      out.write("        ");

            Object usuarioObj = session.getAttribute("usuarioLogueado");
            if(usuarioObj != null) {
                DtUsuario usuario = (DtUsuario) usuarioObj;
        
      out.write("\r\n");
      out.write("            <div style=\"display:flex; align-items:center; gap:10px;\">\r\n");
      out.write("               ");

                   String rutaImagen = usuario.getImagen();
                   if (rutaImagen == null || rutaImagen.isEmpty()) {
                       rutaImagen = request.getContextPath() + "/imagenes/usuarioDefault.png";
                   } else {
                       // Llamar al Web Service SOAP para obtener la imagen en Base64
                       ImagenWSEndpointService imagenServicio = new ImagenWSEndpointService();
                       IImagenControllerWS imagenWS = imagenServicio.getImagenWSEndpointPort();
                       rutaImagen = imagenWS.obtenerImagenBase64(rutaImagen);
                   }
               
      out.write("\r\n");
      out.write("               <img src=\"");
      out.print( rutaImagen );
      out.write("\" alt=\"Imagen de Usuario\" style=\"width:40px; height:40px; border-radius:50%;\">\r\n");
      out.write("               <div style=\"display:flex; flex-direction:column;\">\r\n");
      out.write("                    <span>");
      out.print( usuario.getNombre() );
      out.write(' ');
      out.print( usuario.getApellido() );
      out.write("</span>\r\n");
      out.write("                    <span style=\"font-size:13px;\">\r\n");
      out.write("                        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/consultaPerfilUsuario?nick=");
      out.print( usuario.getNickname() );
      out.write("\" style=\"text-decoration:none; color:#333;\">Perfil</a> |\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cierreSesion\" style=\"text-decoration:none; color:#333;\">Cerrar Sesión </a>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("            <a href=\"altaPerfil\">REGISTRARSE</a> |\r\n");
      out.write("            <a href=\"inicioDeSesion\">ENTRAR</a>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("        const menuToggle = document.getElementById('menuToggle');\r\n");
      out.write("        const sidebarMenu = document.getElementById('sidebarMenu');\r\n");
      out.write("        const sidebarClose = document.getElementById('sidebarClose');\r\n");
      out.write("        const sidebarOverlay = document.getElementById('sidebarOverlay');\r\n");
      out.write("\r\n");
      out.write("        function openMenu() {\r\n");
      out.write("            sidebarMenu.classList.add('active');\r\n");
      out.write("            sidebarOverlay.classList.add('active');\r\n");
      out.write("            menuToggle.style.display = 'none';\r\n");
      out.write("            document.body.style.overflow = 'hidden';\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function closeMenu() {\r\n");
      out.write("            sidebarMenu.classList.remove('active');\r\n");
      out.write("            sidebarOverlay.classList.remove('active');\r\n");
      out.write("            menuToggle.style.display = '';\r\n");
      out.write("            document.body.style.overflow = '';\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        if (menuToggle) menuToggle.addEventListener('click', openMenu);\r\n");
      out.write("        if (sidebarClose) sidebarClose.addEventListener('click', closeMenu);\r\n");
      out.write("        if (sidebarOverlay) sidebarOverlay.addEventListener('click', closeMenu);\r\n");
      out.write("\r\n");
      out.write("        document.addEventListener('keydown', function(e) {\r\n");
      out.write("            if (e.key === 'Escape' && sidebarMenu.classList.contains('active')) {\r\n");
      out.write("                closeMenu();\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
