/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.48
 * Generated at: 2025-11-19 21:20:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import culturarte.servicios.cliente.usuario.*;
import culturarte.servicios.cliente.propuestas.DtPropuesta;
import culturarte.servicios.cliente.imagenes.*;
import com.culturarteWeb.util.WSFechaUsuario;
import java.time.format.DateTimeFormatter;

public final class consultaPerfilUsuario_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(8);
    _jspx_imports_packages.add("culturarte.servicios.cliente.imagenes");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("culturarte.servicios.cliente.usuario");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.culturarteWeb.util.WSFechaUsuario");
    _jspx_imports_classes.add("culturarte.servicios.cliente.propuestas.DtPropuesta");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Perfil de Usuario</title>\r\n");
      out.write("    <meta charset=\"utf-8\"/>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "estiloCabezalComun.jsp", out, false);
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-light\">\r\n");
 String ctx = request.getContextPath(); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container py-4\">\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "cabezalComun.jsp", out, false);
      out.write("\r\n");
      out.write("    <h1 class=\"h3 mb-4\">Consulta de Perfil de Usuario</h1>\r\n");
      out.write("\r\n");
      out.write("    ");

        Object err = request.getAttribute("error");
        if (err != null) {
    
      out.write("\r\n");
      out.write("    <div class=\"alert alert-danger\">");
      out.print( err );
      out.write("</div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

        List<Map<String, Object>> usuariosCombo =
                (List<Map<String, Object>>) request.getAttribute("usuariosCombo");

        DtUsuario usuario = null;
        boolean esProponenteC = false;
        Boolean esPropio = null;
        boolean esColaboradorC = false;

        boolean esProponente = false;
        boolean esColaborador = false;

        if (usuariosCombo != null) {
    
      out.write("\r\n");
      out.write("    <div class=\"card shadow-sm mb-4\">\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("            <div class=\"d-flex justify-content-between align-items-center flex-wrap gap-2 mb-3\">\r\n");
      out.write("                <h2 class=\"h5 mb-0\">Elegí un usuario</h2>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"input-group\" style=\"max-width: 420px;\">\r\n");
      out.write("        <span class=\"input-group-text\">\r\n");
      out.write("          <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\"\r\n");
      out.write("               class=\"bi bi-search\" viewBox=\"0 0 16 16\">\r\n");
      out.write("            <path d=\"M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85zm-5.242.656a5 5 0 1 1 0-10 5 5 0 0 1 0 10z\"/>\r\n");
      out.write("          </svg>\r\n");
      out.write("        </span>\r\n");
      out.write("                    <input id=\"filtroUsuarios\" type=\"text\" class=\"form-control\"\r\n");
      out.write("                           placeholder=\"Buscar por nick, nombre o apellido...\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row g-3\" id=\"gridUsuarios\">\r\n");
      out.write("                ");

                    for (Map<String, Object> u : usuariosCombo) {
                        String nickOpt     = String.valueOf(u.get("nick"));
                        String nombreOpt   = String.valueOf(u.getOrDefault("nombre",""));
                        String apellidoOpt = String.valueOf(u.getOrDefault("apellido",""));
                        String tipoOpt     = String.valueOf(u.getOrDefault("tipo","Usuario"));
                        String img         = (String) u.get("imagen");
                        String rutaImagen;
                        if (img == null || img.isBlank()) {
                            rutaImagen = ctx + "/imagenes/usuarioDefault.png";
                        } else {
                            // Llamar al Web Service SOAP para obtener la imagen en Base64
                            // Crear el servicio para cada usuario (igual que en el perfil individual)
                            try {
                                ImagenWSEndpointService imagenServicio = new ImagenWSEndpointService();
                                IImagenControllerWS imagenWS = imagenServicio.getImagenWSEndpointPort();
                                rutaImagen = imagenWS.obtenerImagenBase64(img);
                                // Verificar que se obtuvo una respuesta válida (debe empezar con "data:image")
                                if (rutaImagen == null || rutaImagen.trim().isEmpty() || !rutaImagen.startsWith("data:image")) {
                                    rutaImagen = ctx + "/imagenes/usuarioDefault.png";
                                }
                            } catch (java.lang.Exception e) {
                                // Si falla, usar imagen por defecto
                                rutaImagen = ctx + "/imagenes/usuarioDefault.png";
                            }
                        }

                        String badgeClass = "text-bg-secondary";
                        if ("Proponente".equalsIgnoreCase(tipoOpt))  badgeClass = "text-bg-primary";
                        else if ("Colaborador".equalsIgnoreCase(tipoOpt)) badgeClass = "text-bg-success";
                
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-sm-6 col-lg-4 col-xl-3 user-card\"\r\n");
      out.write("                     data-nick=\"");
      out.print( nickOpt.toLowerCase() );
      out.write("\"\r\n");
      out.write("                     data-nombre=\"");
      out.print( nombreOpt.toLowerCase() );
      out.write("\"\r\n");
      out.write("                     data-apellido=\"");
      out.print( apellidoOpt.toLowerCase() );
      out.write("\">\r\n");
      out.write("                    <div class=\"card h-100 shadow-sm\">\r\n");
      out.write("                        <div class=\"card-body d-flex gap-3\">\r\n");
      out.write("                            <img src=\"");
      out.print( rutaImagen );
      out.write("\" alt=\"avatar\" class=\"rounded-circle border\"\r\n");
      out.write("                                 style=\"width:64px;height:64px;object-fit:cover\"\r\n");
      out.write("                                 onerror=\"this.src='");
      out.print( ctx );
      out.write("/imagenes/usuarioDefault.png'\">\r\n");
      out.write("                            <div class=\"flex-grow-1\">\r\n");
      out.write("                                <div class=\"d-flex align-items-center gap-2 mb-1\">\r\n");
      out.write("                                    <span class=\"badge ");
      out.print( badgeClass );
      out.write('"');
      out.write('>');
      out.print( tipoOpt );
      out.write("</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"fw-semibold\">");
      out.print( nickOpt );
      out.write("</div>\r\n");
      out.write("                                <div class=\"text-muted small\">");
      out.print( nombreOpt );
      out.write(' ');
      out.print( apellidoOpt );
      out.write("</div>\r\n");
      out.write("                                <div class=\"mt-2\">\r\n");
      out.write("                                    <a class=\"btn btn-sm btn-primary\"\r\n");
      out.write("                                       href=\"");
      out.print( ctx );
      out.write("/consultaPerfilUsuario?nick=");
      out.print( nickOpt );
      out.write("\">\r\n");
      out.write("                                        Ver perfil\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        (function() {\r\n");
      out.write("            const input = document.getElementById('filtroUsuarios');\r\n");
      out.write("            const cards = document.querySelectorAll('#gridUsuarios .user-card');\r\n");
      out.write("            if (!input) return;\r\n");
      out.write("\r\n");
      out.write("            input.addEventListener('input', function () {\r\n");
      out.write("                const q = this.value.trim().toLowerCase();\r\n");
      out.write("                cards.forEach(card => {\r\n");
      out.write("                    const nick = card.dataset.nick || \"\";\r\n");
      out.write("                    const nombre = card.dataset.nombre || \"\";\r\n");
      out.write("                    const apellido = card.dataset.apellido || \"\";\r\n");
      out.write("                    const match = !q || nick.includes(q) || nombre.includes(q) || apellido.includes(q);\r\n");
      out.write("                    card.classList.toggle('d-none', !match);\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        })();\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    ");

    } else {
        usuario = (DtUsuario) request.getAttribute("usuarioConsultado");
        esPropio = (Boolean) request.getAttribute("esPropio");
        esProponenteC = request.getAttribute("esProponenteC") != null && (Boolean) request.getAttribute("esProponenteC");
        esColaboradorC = request.getAttribute("esColaboradorC") != null && (Boolean) request.getAttribute("esColaboradorC");

        esProponente = request.getAttribute("esProponente") != null && (Boolean) request.getAttribute("esProponente");
        esColaborador = request.getAttribute("esColaborador") != null && (Boolean) request.getAttribute("esColaborador");

        List<String> siguiendoProponentes = (List<String>) request.getAttribute("siguiendoProponentes");
        List<String> siguiendoColaboradores = (List<String>) request.getAttribute("siguiendoColaboradores");
        List<String> followersProponentes = (List<String>) request.getAttribute("followersProponentes");
        List<String> followersColaboradores = (List<String>) request.getAttribute("followersColaboradores");

        List<DtPropuesta> favoritas = (List<DtPropuesta>) request.getAttribute("favoritas");
        List<culturarte.servicios.cliente.usuario.DtPropuesta> publicadasNoIngresada = (List<culturarte.servicios.cliente.usuario.DtPropuesta>) request.getAttribute("publicadasNoIngresada");
        List<culturarte.servicios.cliente.usuario.DtPropuesta> colaboradas = (List<culturarte.servicios.cliente.usuario.DtPropuesta>) request.getAttribute("colaboradas");
        List<culturarte.servicios.cliente.usuario.DtPropuesta> creadasIngresadas = (List<culturarte.servicios.cliente.usuario.DtPropuesta>) request.getAttribute("creadasIngresadas");
        List<DtColaboracion> misColaboraciones = (List<DtColaboracion>) request.getAttribute("misColaboraciones");

        String bio = (String) request.getAttribute("bio");
        String sitioWeb = (String) request.getAttribute("sitioWeb");
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card shadow-sm mb-4\">\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("            <h2 class=\"h4 mb-3\">Perfil de ");
      out.print( (usuario != null ? usuario.getNickname() : request.getParameter("nick")) );
      out.write("</h2>\r\n");
      out.write("            <div class=\"d-flex gap-3 align-items-start\">\r\n");
      out.write("\r\n");
      out.write("                ");
String rutaImagen = (usuario != null) ? usuario.getImagen() : null;
                    if (rutaImagen == null || rutaImagen.isBlank()) {
                        rutaImagen = ctx + "/imagenes/usuarioDefault.png";
                    } else {
                        // Llamar al Web Service SOAP para obtener la imagen en Base64
                        try {
                            ImagenWSEndpointService imagenServicio = new ImagenWSEndpointService();
                            IImagenControllerWS imagenWS = imagenServicio.getImagenWSEndpointPort();
                            rutaImagen = imagenWS.obtenerImagenBase64(rutaImagen);
                            // Verificar que se obtuvo una respuesta válida
                            if (rutaImagen == null || rutaImagen.trim().isEmpty() || !rutaImagen.startsWith("data:image")) {
                                rutaImagen = ctx + "/imagenes/usuarioDefault.png";
                            }
                        } catch (java.lang.Exception e) {
                            // Si falla, usar imagen por defecto
                            rutaImagen = ctx + "/imagenes/usuarioDefault.png";
                        }
                    }
      out.write("\r\n");
      out.write("                <img alt=\"avatar\" src=\"");
      out.print( rutaImagen );
      out.write("\" class=\"rounded-circle border\" style=\"width:96px;height:96px;object-fit:cover\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class=\"mb-1\">\r\n");
      out.write("                        <span class=\"badge ");
      out.print( esProponenteC ? "text-bg-primary" : (esColaboradorC ? "text-bg-success" : "text-bg-secondary") );
      out.write("\">\r\n");
      out.write("                            ");
      out.print( esProponenteC ? "Proponente" : (esColaboradorC ? "Colaborador" : "Usuario") );
      out.write("\r\n");
      out.write("                        </span>\r\n");
      out.write("                        ");
 if (esPropio != null && esPropio) { 
      out.write("\r\n");
      out.write("                        <span class=\"ms-2 text-muted small\">Estás viendo tu propio perfil</span>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
 if (usuario != null) { 
      out.write("\r\n");
      out.write("                    <div><b>Nombre:</b> ");
      out.print(usuario.getNombre());
      out.write(' ');
      out.print(usuario.getApellido());
      out.write("</div>\r\n");
      out.write("                    <div><b>Correo:</b> ");
      out.print(usuario.getCorreo());
      out.write("</div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    ");

                        if (esProponenteC) {

                            if (bio != null && !bio.isBlank()) { 
      out.write("\r\n");
      out.write("                    <div><b>Biografía:</b> ");
      out.print(bio);
      out.write("</div>\r\n");
      out.write("                    ");
 }

                        if (sitioWeb != null && !sitioWeb.isBlank()) {
                            String sitioWebURL = sitioWeb;
                            if (!sitioWebURL.toLowerCase().startsWith("http")) {
                                sitioWebURL = "http://" + sitioWebURL;
                            }
                    
      out.write("\r\n");
      out.write("                    <div><b>Sitio Web:</b> <a href=\"");
      out.print(sitioWebURL);
      out.write("\" target=\"_blank\">");
      out.print(sitioWeb);
      out.write("</a></div>\r\n");
      out.write("                    ");
 }
                    }
                    
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row g-4\">\r\n");
      out.write("        <!-- Seguidores -->\r\n");
      out.write("        <div class=\"col-12 col-lg-6\">\r\n");
      out.write("            <div class=\"card shadow-sm h-100\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h3 class=\"h5\">Seguidores</h3>\r\n");
      out.write("                    <table class=\"table table-sm table-bordered align-middle mb-0\">\r\n");
      out.write("                        <thead class=\"table-light\">\r\n");
      out.write("                        <tr><th>Nickname</th><th>Tipo</th><th class=\"text-center\">Acciones</th></tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                        ");
 boolean hayFollowers = false; 
      out.write("\r\n");
      out.write("                        ");
 if (followersProponentes != null) {
                            for (String n : followersProponentes) { hayFollowers = true; 
      out.write("\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>");
      out.print(n);
      out.write("</td>\r\n");
      out.write("                            <td><span class=\"badge text-bg-primary\">Proponente</span></td>\r\n");
      out.write("                            <td class=\"text-center\"><a class=\"btn btn-link btn-sm\" href=\"");
      out.print(ctx);
      out.write("/consultaPerfilUsuario?nick=");
      out.print(n);
      out.write("\">Ver perfil</a></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        ");
 } } 
      out.write("\r\n");
      out.write("                        ");
 if (followersColaboradores != null) {
                            for (String n : followersColaboradores) { hayFollowers = true; 
      out.write("\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>");
      out.print(n);
      out.write("</td>\r\n");
      out.write("                            <td><span class=\"badge text-bg-success\">Colaborador</span></td>\r\n");
      out.write("                            <td class=\"text-center\"><a class=\"btn btn-link btn-sm\" href=\"");
      out.print(ctx);
      out.write("/consultaPerfilUsuario?nick=");
      out.print(n);
      out.write("\">Ver perfil</a></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        ");
 } } 
      out.write("\r\n");
      out.write("                        ");
 if (!hayFollowers) { 
      out.write("\r\n");
      out.write("                        <tr><td colspan=\"3\" class=\"text-center text-muted\">(sin seguidores)</td></tr>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-12 col-lg-6\">\r\n");
      out.write("            <div class=\"card shadow-sm h-100\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h3 class=\"h5\">Siguiendo</h3>\r\n");
      out.write("                    <table class=\"table table-sm table-bordered align-middle mb-0\">\r\n");
      out.write("                        <thead class=\"table-light\">\r\n");
      out.write("                        <tr><th>Nickname</th><th>Tipo</th><th class=\"text-center\">Acciones</th></tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                        ");
 boolean haySiguiendo = false; 
      out.write("\r\n");
      out.write("                        ");
 if (siguiendoProponentes != null) {
                            for (String n : siguiendoProponentes) { haySiguiendo = true; 
      out.write("\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>");
      out.print(n);
      out.write("</td>\r\n");
      out.write("                            <td><span class=\"badge text-bg-primary\">Proponente</span></td>\r\n");
      out.write("                            <td class=\"text-center\"><a class=\"btn btn-link btn-sm\" href=\"");
      out.print(ctx);
      out.write("/consultaPerfilUsuario?nick=");
      out.print(n);
      out.write("\">Ver perfil</a></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        ");
 } } 
      out.write("\r\n");
      out.write("                        ");
 if (siguiendoColaboradores != null) {
                            for (String n : siguiendoColaboradores) { haySiguiendo = true; 
      out.write("\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>");
      out.print(n);
      out.write("</td>\r\n");
      out.write("                            <td><span class=\"badge text-bg-success\">Colaborador</span></td>\r\n");
      out.write("                            <td class=\"text-center\"><a class=\"btn btn-link btn-sm\" href=\"");
      out.print(ctx);
      out.write("/consultaPerfilUsuario?nick=");
      out.print(n);
      out.write("\">Ver perfil</a></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        ");
 } } 
      out.write("\r\n");
      out.write("                        ");
 if (!haySiguiendo) { 
      out.write("\r\n");
      out.write("                        <tr><td colspan=\"3\" class=\"text-center text-muted\">(no sigue a nadie)</td></tr>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-12\">\r\n");
      out.write("            <div class=\"card shadow-sm\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h3 class=\"h5\">Propuestas favoritas</h3>\r\n");
      out.write("                    <table class=\"table table-sm table-bordered align-middle mb-0\">\r\n");
      out.write("                        <thead class=\"table-light\">\r\n");
      out.write("                        <tr><th>Título</th><th class=\"text-center\">Acciones</th></tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                        ");
 if (favoritas != null && !favoritas.isEmpty()) {
                            for (culturarte.servicios.cliente.propuestas.DtPropuesta p : favoritas) { 
      out.write("\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>");
      out.print( p.getTitulo() );
      out.write("</td>\r\n");
      out.write("                            <td class=\"text-center\">\r\n");
      out.write("                                <a class=\"btn btn-link btn-sm\" href=\"");
      out.print(ctx);
      out.write("/consultaPropuesta?accion=detalle&titulo=");
      out.print( p.getTitulo() );
      out.write("\">Ver detalle</a>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        ");
 } } else { 
      out.write("\r\n");
      out.write("                        <tr><td colspan=\"2\" class=\"text-center text-muted\">(sin favoritas)</td></tr>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");
 if (esProponenteC) { 
      out.write("\r\n");
      out.write("        <div class=\"col-12\">\r\n");
      out.write("            <div class=\"card shadow-sm\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h3 class=\"h5\">Publicadas</h3>\r\n");
      out.write("                    <table class=\"table table-sm table-bordered align-middle mb-0\">\r\n");
      out.write("                        <thead class=\"table-light\">\r\n");
      out.write("                        <tr><th>Título</th><th>Estado</th><th class=\"text-center\">Acciones</th></tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                        ");
 if (publicadasNoIngresada != null && !publicadasNoIngresada.isEmpty()) {
                            for (culturarte.servicios.cliente.usuario.DtPropuesta p : publicadasNoIngresada) { 
      out.write("\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>");
      out.print(p.getTitulo());
      out.write("</td>\r\n");
      out.write("                            <td><span class=\"badge text-bg-secondary\">");
      out.print(p.getEstadoActual() != null ? p.getEstadoActual().toString() : "");
      out.write("</span></td>\r\n");
      out.write("                            <td class=\"text-center\"><a class=\"btn btn-link btn-sm\" href=\"");
      out.print(ctx);
      out.write("/consultaPropuesta?accion=detalle&titulo=");
      out.print(p.getTitulo());
      out.write("\">Ver detalle</a></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        ");
 } } else { 
      out.write("\r\n");
      out.write("                        <tr><td colspan=\"3\" class=\"text-center text-muted\">(sin propuestas publicadas fuera de INGRESADA)</td></tr>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 if (esColaboradorC) { 
      out.write("\r\n");
      out.write("        <!-- Colaboradas -->\r\n");
      out.write("        <div class=\"col-12\">\r\n");
      out.write("            <div class=\"card shadow-sm\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h3 class=\"h5\">Propuestas colaboradas</h3>\r\n");
      out.write("                    <table class=\"table table-sm table-bordered align-middle mb-0\">\r\n");
      out.write("                        <thead class=\"table-light\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>Título</th><th>Fecha y Hora</th><th>Monto</th><th>Acciones</th>\r\n");
      out.write("                        </thead>\r\n");
      out.write("\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                        ");
 if (colaboradas != null && !colaboradas.isEmpty()) {
                            for (DtColaboracion m : misColaboraciones) {
                                culturarte.servicios.cliente.usuario.DtPropuesta prop = m.getPropuesta();
                        
      out.write("\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>");
      out.print(prop.getTitulo());
      out.write("</td>\r\n");
      out.write("                            ");
      out.write("\r\n");
      out.write("                            ");
 if (esPropio != null && esPropio ){
      out.write("\r\n");
      out.write("                            <td>");

                                String fechaHoraStr = "Fecha no disponible";
                                if (m.getFechaHora() != null) {
                                    try {
                                        java.time.LocalDateTime fechaHora = WSFechaUsuario.toJavaLocalDateTime(m.getFechaHora());
                                        if (fechaHora != null) {
                                            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
                                            fechaHoraStr = fechaHora.format(formatter);
                                        }
                                    } catch (java.lang.Exception e) {
                                        fechaHoraStr = "Fecha no disponible";
                                    }
                                }
                                out.print(fechaHoraStr);
                            
      out.write("</td>\r\n");
      out.write("                            <td>$");
      out.print( String.format("%.2f", m.getMonto()) );
      out.write("</td>\r\n");
      out.write("                            ");
}else{
      out.write("\r\n");
      out.write("                            <td>-</td>\r\n");
      out.write("                            <td>-</td>\r\n");
      out.write("                            ");
}
      out.write("\r\n");
      out.write("                            <td class=\"text-center\"><a class=\"btn btn-link btn-sm\" href=\"");
      out.print(ctx);
      out.write("/consultaPropuesta?accion=detalle&titulo=");
      out.print(prop.getTitulo());
      out.write("\">Ver detalle</a></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        ");
 }}  else { 
      out.write("\r\n");
      out.write("                        <tr><td colspan=\"4\" class=\"text-center text-muted\">(sin colaboraciones)</td></tr>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 if (esPropio != null && esPropio && esProponenteC) { 
      out.write("\r\n");
      out.write("        <div class=\"col-12\">\r\n");
      out.write("            <div class=\"card shadow-sm\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h3 class=\"h5\">Mis propuestas en estado INGRESADA</h3>\r\n");
      out.write("                    <table class=\"table table-sm table-bordered align-middle mb-0\">\r\n");
      out.write("                        <thead class=\"table-light\">\r\n");
      out.write("                        <tr><th>Título</th><th>Estado</th><th class=\"text-center\">Acciones</th></tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                        ");
 if (creadasIngresadas != null && !creadasIngresadas.isEmpty()) {
                            for (culturarte.servicios.cliente.usuario.DtPropuesta p : creadasIngresadas) { 
      out.write("\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>");
      out.print(p.getTitulo());
      out.write("</td>\r\n");
      out.write("                            <td><span class=\"badge text-bg-secondary\">");
      out.print(p.getEstadoActual() != null ? p.getEstadoActual().toString() : "");
      out.write("</span></td>\r\n");
      out.write("                            <td class=\"text-center\"><a class=\"btn btn-link btn-sm\" href=\"");
      out.print(ctx);
      out.write("/consultaPropuesta?accion=detalle&titulo=");
      out.print(p.getTitulo());
      out.write("\">Ver detalle</a></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        ");
 } } else { 
      out.write("\r\n");
      out.write("                        <tr><td colspan=\"3\" class=\"text-center text-muted\">(sin propuestas en estado INGRESADA)</td></tr>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"d-flex gap-2 mt-4\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-outline-secondary\"\r\n");
      out.write("                onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/principal'\">Volver al inicio\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("        ");

            DtUsuario usuarioConsultadoBtn = (DtUsuario) request.getAttribute("usuarioConsultado");
            String nickConsultadoBtn = (usuarioConsultadoBtn != null)
                    ? usuarioConsultadoBtn.getNickname()
                    : request.getParameter("nick");

            DtUsuario usuarioActualBtn = (DtUsuario) session.getAttribute("usuarioLogueado");
            Boolean esPropioBtn = (Boolean) request.getAttribute("esPropio");
            boolean puedeSeguir = (usuarioActualBtn != null) && Boolean.FALSE.equals(esPropioBtn);
            boolean loSigo = Boolean.TRUE.equals(request.getAttribute("loSigo"));
            if (puedeSeguir) {
        
      out.write("\r\n");
      out.write("        <form method=\"post\" action=\"");
      out.print( ctx );
      out.write("/seguimientoDeUsuario\">\r\n");
      out.write("            <input type=\"hidden\" name=\"seguido\" value=\"");
      out.print( nickConsultadoBtn );
      out.write("\">\r\n");
      out.write("            <button type=\"submit\" class=\"btn ");
      out.print( loSigo ? "btn-outline-danger" : "btn-primary" );
      out.write("\">\r\n");
      out.write("                ");
      out.print( loSigo ? "Dejar de seguir" : "Seguir" );
      out.write("\r\n");
      out.write("            </button>\r\n");
      out.write("        </form>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        ");
 if (esPropio != null && esPropio && esProponenteC) { 
      out.write("\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/bajaProponente\"\r\n");
      out.write("           class=\"btn btn-danger\">\r\n");
      out.write("            <i class=\"bi bi-trash\"></i> Dar de Baja Mi Cuenta\r\n");
      out.write("        </a>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");
 } // fin if usuariosCombo 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
