/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.48
 * Generated at: 2025-11-19 21:20:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import culturarte.servicios.cliente.propuestas.DtPropuesta;
import culturarte.servicios.cliente.propuestas.DtCategoria;
import culturarte.servicios.cliente.imagenes.*;

public final class listaPropuestas_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("culturarte.servicios.cliente.imagenes");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("culturarte.servicios.cliente.propuestas.DtCategoria");
    _jspx_imports_classes.add("culturarte.servicios.cliente.propuestas.DtPropuesta");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Consulta de Propuestas - Culturarte</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "estiloCabezalComun.jsp", out, false);
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-light\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "cabezalComun.jsp", out, false);
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"py-3 py-md-5\">\r\n");
      out.write("    <div class=\"row justify-content-center\">\r\n");
      out.write("        <div class=\"col-12 col-md-10\">\r\n");
      out.write("            <div class=\"card shadow-sm\">\r\n");
      out.write("                <div class=\"card-header\">\r\n");
      out.write("                    <h3 class=\"text-center mb-0\">Consulta de Propuestas</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    \r\n");
      out.write("                    ");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("                        <div class=\"alert alert-danger\" role=\"alert\">\r\n");
      out.write("                            ");
      out.print( request.getAttribute("error") );
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"row mb-4\">\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <div class=\"card bg-light\">\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <h5 class=\"card-title mb-3\">\r\n");
      out.write("                                        <i class=\"bi bi-funnel\"></i> Filtros de Búsqueda\r\n");
      out.write("                                    </h5>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <form method=\"get\" action=\"");
      out.print( request.getContextPath() );
      out.write("/consultaPropuesta\">\r\n");
      out.write("                                        <div class=\"row g-3\">\r\n");
      out.write("                                            <div class=\"col-12 col-sm-6 col-md-4\">\r\n");
      out.write("                                                <label for=\"busqueda\" class=\"form-label\">Buscar</label>\r\n");
      out.write("                                                <input type=\"text\" class=\"form-control\" id=\"busqueda\" name=\"busqueda\" \r\n");
      out.write("                                                       placeholder=\"Título, descripción o lugar...\" \r\n");
      out.write("                                                       value=\"");
      out.print( request.getAttribute("busqueda") != null ? request.getAttribute("busqueda") : "" );
      out.write("\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div class=\"col-12 col-sm-6 col-md-3\">\r\n");
      out.write("                                                <label for=\"estado\" class=\"form-label\">Estado</label>\r\n");
      out.write("                                                <select class=\"form-select\" id=\"estado\" name=\"estado\">\r\n");
      out.write("                                                    <option value=\"todas\" ");
      out.print( "todas".equals(request.getAttribute("estadoFiltro")) ? "selected" : "" );
      out.write(">Todas</option>\r\n");
      out.write("                                                    <option value=\"en_financiacion\" ");
      out.print( "en_financiacion".equals(request.getAttribute("estadoFiltro")) ? "selected" : "" );
      out.write(">En Financiación</option>\r\n");
      out.write("                                                    <option value=\"financiadas\" ");
      out.print( "financiadas".equals(request.getAttribute("estadoFiltro")) ? "selected" : "" );
      out.write(">Financiadas</option>\r\n");
      out.write("                                                    <option value=\"no_financiadas\" ");
      out.print( "no_financiadas".equals(request.getAttribute("estadoFiltro")) ? "selected" : "" );
      out.write(">No Financiadas</option>\r\n");
      out.write("                                                    <option value=\"canceladas\" ");
      out.print( "canceladas".equals(request.getAttribute("estadoFiltro")) ? "selected" : "" );
      out.write(">Canceladas</option>\r\n");
      out.write("                                                </select>\r\n");
      out.write("                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div class=\"col-12 col-sm-6 col-md-3\">\r\n");
      out.write("                                                <label for=\"categoria\" class=\"form-label\">Categoría</label>\r\n");
      out.write("                                                <select class=\"form-select\" id=\"categoria\" name=\"categoria\">\r\n");
      out.write("                                                    <option value=\"todas\" ");
      out.print( "todas".equals(request.getAttribute("categoriaFiltro")) ? "selected" : "" );
      out.write(">Todas</option>\r\n");
      out.write("                                                    ");
 
                                                    List<DtCategoria> categorias = (List<DtCategoria>) request.getAttribute("categorias");
                                                    if (categorias != null) {
                                                        for (DtCategoria categoria : categorias) {
                                                            String nombreCategoria = categoria.getNombre();
                                                            boolean selected = nombreCategoria.equals(request.getAttribute("categoriaFiltro"));
                                                    
      out.write("\r\n");
      out.write("                                                        <option value=\"");
      out.print( nombreCategoria );
      out.write('"');
      out.write(' ');
      out.print( selected ? "selected" : "" );
      out.write('>');
      out.print( nombreCategoria );
      out.write("</option>\r\n");
      out.write("                                                    ");
 
                                                        }
                                                    }
                                                    
      out.write("\r\n");
      out.write("                                                </select>\r\n");
      out.write("                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div class=\"col-12 col-sm-6 col-md-2\">\r\n");
      out.write("                                                <label for=\"ordenarPor\" class=\"form-label\">Ordenar por</label>\r\n");
      out.write("                                                <select class=\"form-select\" id=\"ordenarPor\" name=\"ordenarPor\">\r\n");
      out.write("                                                    <option value=\"\" ");
      out.print( request.getAttribute("ordenarPor") == null || request.getAttribute("ordenarPor").equals("") ? "selected" : "" );
      out.write(">Sin ordenar</option>\r\n");
      out.write("                                                    <option value=\"alfabetico\" ");
      out.print( "alfabetico".equals(request.getAttribute("ordenarPor")) ? "selected" : "" );
      out.write(">Alfabético</option>\r\n");
      out.write("                                                    <option value=\"fecha_creacion\" ");
      out.print( "fecha_creacion".equals(request.getAttribute("ordenarPor")) ? "selected" : "" );
      out.write(">Fecha de creación</option>\r\n");
      out.write("                                                    <option value=\"monto_ascendente\" ");
      out.print( "monto_ascendente".equals(request.getAttribute("ordenarPor")) ? "selected" : "" );
      out.write(">Monto (menor a mayor)</option>\r\n");
      out.write("                                                    <option value=\"monto_descendente\" ");
      out.print( "monto_descendente".equals(request.getAttribute("ordenarPor")) ? "selected" : "" );
      out.write(">Monto (mayor a menor)</option>\r\n");
      out.write("                                                </select>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                        <div class=\"row mt-3\">\r\n");
      out.write("                                            <div class=\"col-12\">\r\n");
      out.write("                                                <button type=\"submit\" class=\"btn btn-primary\">\r\n");
      out.write("                                                    <i class=\"bi bi-search\"></i> Buscar\r\n");
      out.write("                                                </button>\r\n");
      out.write("                                                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/consultaPropuesta\" class=\"btn btn-outline-secondary\">\r\n");
      out.write("                                                    <i class=\"bi bi-arrow-clockwise\"></i> Limpiar Filtros\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </form>\r\n");
      out.write("\r\n");
      out.write("                                    ");
 if (request.getAttribute("totalResultados") != null) { 
      out.write("\r\n");
      out.write("                                        <div class=\"mt-3\">\r\n");
      out.write("                                            <small class=\"text-muted\">\r\n");
      out.write("                                                <i class=\"bi bi-info-circle\"></i> \r\n");
      out.write("                                                Mostrando ");
      out.print( request.getAttribute("totalResultados") );
      out.write(" resultado(s)\r\n");
      out.write("                                                ");
 if (request.getAttribute("busqueda") != null && !request.getAttribute("busqueda").toString().trim().isEmpty()) { 
      out.write("\r\n");
      out.write("                                                    para \"");
      out.print( request.getAttribute("busqueda") );
      out.write("\"\r\n");
      out.write("                                                ");
 } 
      out.write("\r\n");
      out.write("                                            </small>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    ");
 List<DtPropuesta> propuestas = (List<DtPropuesta>) request.getAttribute("propuestas");
                    if (propuestas != null && !propuestas.isEmpty()) { 
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"row g-3\">\r\n");
      out.write("                            ");
 for (DtPropuesta propuesta : propuestas) { 
      out.write("\r\n");
      out.write("                                <div class=\"col-12 col-sm-6 col-lg-4 mb-3 mb-md-4\">\r\n");
      out.write("                                    <div class=\"card h-100\">\r\n");
      out.write("                                        ");
 
                                        String imagenPropuesta = propuesta.getImagen();
                                        boolean tieneImagen = imagenPropuesta != null && !imagenPropuesta.trim().isEmpty();
                                        
      out.write("\r\n");
      out.write("                                        \r\n");
      out.write("                                        ");
 if (tieneImagen) { 
      out.write("\r\n");
      out.write("                                            ");

                                            // Llamar al Web Service SOAP para obtener la imagen en Base64
                                            ImagenWSEndpointService imagenServicio = new ImagenWSEndpointService();
                                            IImagenControllerWS imagenWS = imagenServicio.getImagenWSEndpointPort();
                                            String imagenDataUri = imagenWS.obtenerImagenBase64(imagenPropuesta);
                                            
      out.write("\r\n");
      out.write("                                            <img src=\"");
      out.print( imagenDataUri );
      out.write("\" \r\n");
      out.write("                                                 class=\"card-img-top\" style=\"height: 200px; object-fit: cover; width: 100%;\" \r\n");
      out.write("                                                 alt=\"Imagen de ");
      out.print( propuesta.getTitulo() );
      out.write("\"\r\n");
      out.write("                                                 onerror=\"this.style.display='none'; this.nextElementSibling.style.display='flex';\">\r\n");
      out.write("                                       ");
 } else { 
      out.write("\r\n");
      out.write("                                           <img src=\"");
      out.print( request.getContextPath() );
      out.write("/imagenes/propuestaDefault.png\"\r\n");
      out.write("                                                class=\"card-img-top\" style=\"height: 200px; object-fit: cover; width: 100%;\"\r\n");
      out.write("                                                alt=\"Imagen por defecto\">\r\n");
      out.write("                                       ");
 } 
      out.write("\r\n");
      out.write("                                        <div class=\"card-body d-flex flex-column\">\r\n");
      out.write("                                            <h5 class=\"card-title\">");
      out.print( propuesta.getTitulo() );
      out.write("</h5>\r\n");
      out.write("                                            <p class=\"card-text text-muted flex-grow-1\" style=\"font-size: 0.9rem;\">\r\n");
      out.write("                                                ");
      out.print( propuesta.getDescripcion() != null && propuesta.getDescripcion().length() > 100 ? 
                                                    propuesta.getDescripcion().substring(0, 100) + "..." : 
                                                    (propuesta.getDescripcion() != null ? propuesta.getDescripcion() : "") );
      out.write("\r\n");
      out.write("                                            </p>\r\n");
      out.write("                                            \r\n");
      out.write("                                            <div class=\"mb-2\">\r\n");
      out.write("                                                <strong>Estado:</strong>\r\n");
      out.write("                                                 ");

                                                 String estado = propuesta.getEstadoActual().toString();
                                                 String estadoFormateado;

                                                 switch (estado) {
                                                    case "INGRESADA": estadoFormateado = "Ingresada"; break;
                                                    case "PUBLICADA": estadoFormateado = "Publicada"; break;
                                                    case "EN_FINANCIACION": estadoFormateado = "En Financiación"; break;
                                                    case "FINANCIADA": estadoFormateado = "Financiada"; break;
                                                    case "NO_FINANCIADA": estadoFormateado = "No Financiada"; break;
                                                    case "CANCELADA": estadoFormateado = "Cancelada"; break;
                                                    default: estadoFormateado = estado;
                                                 }
                                                 
      out.write("\r\n");
      out.write("                                                <span class=\"badge bg-primary\">");
      out.print( estadoFormateado );
      out.write("</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            \r\n");
      out.write("                                            <div class=\"mb-2\">\r\n");
      out.write("                                                <strong>Monto necesario:</strong> \r\n");
      out.write("                                                <span class=\"text-nowrap\">$");
      out.print( String.format("%.2f", propuesta.getMontoNecesario()) );
      out.write("</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            \r\n");
      out.write("                                            <div class=\"mb-2\">\r\n");
      out.write("                                                <strong>Proponente:</strong> \r\n");
      out.write("                                                <span class=\"text-break\">");
      out.print( propuesta.getDTProponente() != null ? 
                                                    propuesta.getDTProponente().getNickname() : "N/A" );
      out.write("</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            \r\n");
      out.write("                                            <div class=\"mb-3\">\r\n");
      out.write("                                                <strong>Fecha publicación:</strong> \r\n");
      out.write("                                                <span class=\"text-nowrap\">\r\n");
      out.write("                                                ");
 
                                                    if (propuesta.getFechaPublicacion() != null) {
                                                        java.time.LocalDate fechaPublicacion = com.culturarteWeb.util.WSFechaPropuesta.toJavaLocalDate(propuesta.getFechaPublicacion());
                                                        out.print(fechaPublicacion != null ? fechaPublicacion.toString() : "N/A");
                                                    } else {
                                                        out.print("N/A");
                                                    }
                                                
      out.write("\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            \r\n");
      out.write("                                            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/consultaPropuesta?accion=detalle&titulo=");
      out.print( 
                                                java.net.URLEncoder.encode(propuesta.getTitulo(), "UTF-8") );
      out.write("\" \r\n");
      out.write("                                               class=\"btn btn-primary w-100 mt-auto\">\r\n");
      out.write("                                                Ver Detalles\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                    ");
 } else { 
      out.write("\r\n");
      out.write("                        <div class=\"text-center py-5\">\r\n");
      out.write("                            <h4 class=\"text-muted\">No hay propuestas disponibles</h4>\r\n");
      out.write("                            <p class=\"text-muted\">No se encontraron propuestas para mostrar.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"text-center mt-4\">\r\n");
      out.write("                        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/principal\" class=\"btn btn-secondary\">\r\n");
      out.write("                            Volver al Inicio\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
