/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.48
 * Generated at: 2025-11-19 22:46:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import culturarte.servicios.cliente.propuestas.DtPropuesta;
import culturarte.servicios.cliente.propuestas.DtCategoria;
import culturarte.servicios.cliente.usuario.DtUsuario;
import com.culturarteWeb.util.WSFechaPropuesta;
import culturarte.servicios.cliente.imagenes.*;

public final class principal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("culturarte.servicios.cliente.imagenes");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("culturarte.servicios.cliente.usuario.DtUsuario");
    _jspx_imports_classes.add("com.culturarteWeb.util.WSFechaPropuesta");
    _jspx_imports_classes.add("culturarte.servicios.cliente.propuestas.DtCategoria");
    _jspx_imports_classes.add("culturarte.servicios.cliente.propuestas.DtPropuesta");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Culturarte</title>\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "estiloCabezalComun.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            background-color: #f5f5f5;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            font-family: 'Arial', sans-serif;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-link.estado-tab {\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            color: #333; /* Color inactivo */\r\n");
      out.write("        }\r\n");
      out.write("        .nav-link.estado-tab:hover {\r\n");
      out.write("            color: #000;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-link.estado-tab.active {\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            background-color: #333;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        .cartaPropuesta {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            transition: transform 0.2s ease-in-out, box-shadow 0.2s ease-in-out;\r\n");
      out.write("            animation: fadeInDesdeAbajo 0.6s ease-out forwards;\r\n");
      out.write("        }\r\n");
      out.write("        .cartaPropuesta .btn {\r\n");
      out.write("                    transition: transform 0.15s ease-in-out;\r\n");
      out.write("                }\r\n");
      out.write("        .cartaPropuesta .btn:hover {\r\n");
      out.write("                    transform: scale(1.03);\r\n");
      out.write("                }\r\n");
      out.write("        .cartaPropuesta:hover {\r\n");
      out.write("                    transform: translateY(-5px);\r\n");
      out.write("                    box-shadow: 0 1rem 3rem rgba(0, 0, 0, .175) !important;\r\n");
      out.write("        }\r\n");
      out.write("        .cartaPropuesta:hover .imagenPropuesta {\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("        }\r\n");
      out.write("        .imagenPropuesta {\r\n");
      out.write("            height: 180px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("            transition: transform 0.2s ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .contenidoPropuesta {\r\n");
      out.write("            padding: 1.25rem;\r\n");
      out.write("            flex-grow: 1;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tituloPropuesta {\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .descripcionPropuesta {\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            color: #666;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("            height: 60px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            display: -webkit-box;\r\n");
      out.write("            -webkit-line-clamp: 3;\r\n");
      out.write("            -webkit-box-orient: vertical;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .progreso-financiacion {\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .info-progreso {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            color: #666;\r\n");
      out.write("            margin-bottom: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .estadisticas-propuesta {\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            color: #666;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .icono {\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            margin-right: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .datosPropuesta {\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            color: #666;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .contenidoPropuesta .btn {\r\n");
      out.write("            margin-top: auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .categorias {\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .itemCategoria {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 8px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 576px) {\r\n");
      out.write("            .estadisticas-propuesta {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                gap: 5px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        @keyframes fadeInDesdeAbajo {\r\n");
      out.write("                    from {\r\n");
      out.write("                        opacity: 0;\r\n");
      out.write("                        transform: translateY(20px);\r\n");
      out.write("                    }\r\n");
      out.write("                    to {\r\n");
      out.write("                        opacity: 1;\r\n");
      out.write("                        transform: translateY(0);\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("        .itemCategoria .form-check-input {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .itemCategoria .form-check-label {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            padding: 8px 16px;\r\n");
      out.write("            border: 1px solid #ddd;\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.2s ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .itemCategoria .form-check-label:hover {\r\n");
      out.write("            background-color: #f5f5f5;\r\n");
      out.write("            border-color: #aaa;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .itemCategoria .form-check-input:checked + .form-check-label {\r\n");
      out.write("            background-color: #333;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border-color: #333;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container my-4\">\r\n");
      out.write("\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "cabezalComun.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 String busquedaActual = (String) request.getAttribute("busqueda"); 
      out.write("\r\n");
      out.write("        ");
 if (busquedaActual != null && !busquedaActual.isEmpty()) { 
      out.write("\r\n");
      out.write("            <div class=\"alert alert-info d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center shadow-sm\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <strong>🔍 Búsqueda activa:</strong> \"");
      out.print( busquedaActual );
      out.write("\"\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <small>\r\n");
      out.write("                        ");
      out.write("\r\n");
      out.write("                        Mostrando ");
      out.print( ((List<com.culturarteWeb.servlets.PrincipalServlet.PropuestaConDatos>) request.getAttribute("propuestas")).size() );
      out.write(" resultado(s)\r\n");
      out.write("                    </small>\r\n");
      out.write("                </div>\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/principal\"\r\n");
      out.write("                   class=\"btn btn-sm btn-outline-danger mt-2 mt-sm-0\">\r\n");
      out.write("                    ✕ Limpiar búsqueda\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <ul class=\"nav nav-pills nav-fill mb-4\">\r\n");
      out.write("            ");

                String estadoFiltro = (String) request.getAttribute("estadoFiltro");
                if (estadoFiltro == null || estadoFiltro.isEmpty()) {
                    estadoFiltro = "todas";
                }
            
      out.write("\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <span class=\"nav-link estado-tab ");
      out.print( "todas".equals(estadoFiltro) ? "active" : "" );
      out.write("\" data-estado=\"todas\">Propuestas Creadas</span>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <span class=\"nav-link estado-tab ");
      out.print( "en_financiacion".equals(estadoFiltro) ? "active" : "" );
      out.write("\" data-estado=\"en_financiacion\">En Financiación</span>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <span class=\"nav-link estado-tab ");
      out.print( "financiadas".equals(estadoFiltro) ? "active" : "" );
      out.write("\" data-estado=\"financiadas\">Financiadas</span>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <span class=\"nav-link estado-tab ");
      out.print( "no_financiadas".equals(estadoFiltro) ? "active" : "" );
      out.write("\" data-estado=\"no_financiadas\">NO Financiadas</span>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <span class=\"nav-link estado-tab ");
      out.print( "canceladas".equals(estadoFiltro) ? "active" : "" );
      out.write("\" data-estado=\"canceladas\">Canceladas</span>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row g-4 mb-4\">\r\n");
      out.write("            ");

                List<com.culturarteWeb.servlets.PrincipalServlet.PropuestaConDatos> propuestas =
                    (List<com.culturarteWeb.servlets.PrincipalServlet.PropuestaConDatos>) request.getAttribute("propuestas");

                if (propuestas != null && !propuestas.isEmpty()) {
                    for (com.culturarteWeb.servlets.PrincipalServlet.PropuestaConDatos propuestaConDatos : propuestas) {
                        DtPropuesta p = propuestaConDatos.getPropuesta();
                        String imagen;
                        if (p.getImagen() != null && !p.getImagen().isEmpty()) {
                            // Llamar al Web Service SOAP para obtener la imagen en Base64
                            ImagenWSEndpointService imagenServicio = new ImagenWSEndpointService();
                            IImagenControllerWS imagenWS = imagenServicio.getImagenWSEndpointPort();
                            imagen = imagenWS.obtenerImagenBase64(p.getImagen());
                        } else {
                            imagen = request.getContextPath() + "/imagenes/propuestaDefault.png";
                        }
                        double porcentajeProgreso = p.getMontoNecesario() > 0 ? (propuestaConDatos.getMontoRecaudado() / p.getMontoNecesario()) * 100 : 0;
                        if (porcentajeProgreso > 100) porcentajeProgreso = 100;

                        long porcentajeRedondeado = Math.round(porcentajeProgreso);
            
      out.write("\r\n");
      out.write("            <div class=\"col-12 col-md-6 col-lg-4 d-flex\">\r\n");
      out.write("                <div class=\"cartaPropuesta h-100 shadow-sm w-100\">\r\n");
      out.write("                    <img src=\"");
      out.print( imagen );
      out.write("\" class=\"imagenPropuesta\" alt=\"Imagen de ");
      out.print( p.getTitulo() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"contenidoPropuesta\">\r\n");
      out.write("                        <div class=\"tituloPropuesta\">");
      out.print( p.getTitulo() );
      out.write("</div>\r\n");
      out.write("                        <div class=\"descripcionPropuesta\">");
      out.print( p.getDescripcion() );
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"progreso-financiacion\">\r\n");
      out.write("                            <div class=\"info-progreso\">\r\n");
      out.write("                                <span>$");
      out.print( String.format("%.0f", propuestaConDatos.getMontoRecaudado()) );
      out.write(" recaudado</span>\r\n");
      out.write("                                <span>");
      out.print( porcentajeRedondeado );
      out.write("%</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"progress\" style=\"height: 8px;\">\r\n");
      out.write("                                <div class=\"progress-bar bg-success\" role=\"progressbar\"\r\n");
      out.write("                                     style=\"width: ");
      out.print( porcentajeRedondeado );
      out.write("%;\"\r\n");
      out.write("                                     aria-valuenow=\"");
      out.print( porcentajeRedondeado );
      out.write("\"\r\n");
      out.write("                                     aria-valuemin=\"0\" ");
      out.write("\r\n");
      out.write("                                     aria-valuemax=\"100\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"estadisticas-propuesta d-flex flex-column flex-sm-row justify-content-sm-between\">\r\n");
      out.write("                            <div class=\"dias-restantes\">\r\n");
      out.write("                                <span class=\"icono\">⏰</span>\r\n");
      out.write("                                <span>");
      out.print( propuestaConDatos.getDiasRestantes() );
      out.write(" días restantes</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"colaboradores-count\">\r\n");
      out.write("                                <span class=\"icono\">👥</span>\r\n");
      out.write("                                <span>");
      out.print( propuestaConDatos.getTotalColaboradores() );
      out.write(" colaboradores</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"datosPropuesta d-flex justify-content-between\">\r\n");
      out.write("                            ");

                            String estado = p.getEstadoActual().toString();
                            String estadoFormateado;

                             switch (estado) {
                                case "INGRESADA": estadoFormateado = "Ingresada"; break;
                                case "PUBLICADA": estadoFormateado = "Publicada"; break;
                                case "EN_FINANCIACION": estadoFormateado = "En Financiación"; break;
                                case "FINANCIADA": estadoFormateado = "Financiada"; break;
                                case "NO_FINANCIADA": estadoFormateado = "No Financiada"; break;
                                case "CANCELADA": estadoFormateado = "Cancelada"; break;
                                default: estadoFormateado = estado;
                            }
                            
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <span>");
      out.print( estadoFormateado );
      out.write("</span>\r\n");
      out.write("                            <span>");
 
                                if (p.getFechaPublicacion() != null) {
                                    java.time.LocalDate fechaPublicacion = WSFechaPropuesta.toJavaLocalDate(p.getFechaPublicacion());
                                    out.print(fechaPublicacion != null ? fechaPublicacion.toString() : "N/A");
                                } else {
                                    out.print("N/A");
                                }
                            
      out.write("</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/consultaPropuesta?accion=detalle&titulo=");
      out.print(
                                java.net.URLEncoder.encode(p.getTitulo(), "UTF-8") );
      out.write("\"\r\n");
      out.write("                           class=\"btn btn-primary w-100\">\r\n");
      out.write("                            Ver Detalles\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");

                    }
                } else {
            
      out.write("\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"alert alert-warning text-center\">\r\n");
      out.write("                        No se encontraron propuestas que coincidan con los filtros seleccionados.\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            ");

                }
            
      out.write("\r\n");
      out.write("        </div> <div class=\"categorias shadow-sm mb-4\">\r\n");
      out.write("            <h3>CATEGORÍAS</h3>\r\n");
      out.write("            <form id=\"filtroCategorias\" method=\"post\" action=\"consultaPropuestaPorCategoria\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row g-3\">\r\n");
      out.write("                    ");

                        List<DtCategoria> categorias = (List<DtCategoria>) request.getAttribute("categorias");
                        String[] categoriasSeleccionadas = (String[]) request.getAttribute("categoriasSeleccionadas");

                        if (categorias != null) {
                            for (DtCategoria categ : categorias) {
                                boolean estaSeleccionada = false;
                                if (categoriasSeleccionadas != null) {
                                    for (String catSel : categoriasSeleccionadas) {
                                        if (catSel.equals(categ.getNombre())) {
                                            estaSeleccionada = true;
                                            break;
                                        }
                                    }
                                }
                    
      out.write("\r\n");
      out.write("                    <div class=\"col-6 col-sm-4 col-md-3 col-lg-2\">\r\n");
      out.write("                        <div class=\"form-check itemCategoria\">\r\n");
      out.write("                            <input class=\"form-check-input\" type=\"checkbox\"\r\n");
      out.write("                                   id=\"");
      out.print( categ.getNombre() );
      out.write("\"\r\n");
      out.write("                                   name=\"categoria\"\r\n");
      out.write("                                   value=\"");
      out.print( categ.getNombre() );
      out.write("\"\r\n");
      out.write("                                   ");
      out.print( estaSeleccionada ? "checked" : "" );
      out.write(">\r\n");
      out.write("                            <label class=\"form-check-label\" for=\"");
      out.print( categ.getNombre() );
      out.write("\">\r\n");
      out.write("                                ");
      out.print( categ.getNombre() );
      out.write("\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");

                            }
                        }
                    
      out.write("\r\n");
      out.write("                </div> <div class=\"mt-4\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-dark\">\r\n");
      out.write("                        Filtrar por Categorías\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <button type=\"button\" onclick=\"limpiarFiltros()\" class=\"btn btn-outline-secondary ms-2\">\r\n");
      out.write("                        Limpiar Filtros\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div> <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        document.querySelectorAll('.estado-tab').forEach(tab => {\r\n");
      out.write("            tab.addEventListener('click', function() {\r\n");
      out.write("                const estado = this.getAttribute('data-estado');\r\n");
      out.write("                const url = new URL(window.location.origin + window.location.pathname);\r\n");
      out.write("\r\n");
      out.write("                url.searchParams.set('estado', estado);\r\n");
      out.write("\r\n");
      out.write("                const busquedaActual = '");
      out.print( busquedaActual != null ? busquedaActual : "" );
      out.write("';\r\n");
      out.write("                if (busquedaActual) {\r\n");
      out.write("                    url.searchParams.set('busqueda', busquedaActual);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                window.location.href = url.toString();\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        function limpiarFiltros() {\r\n");
      out.write("            document.querySelectorAll('input[name=\"categoria\"]').forEach(checkbox => {\r\n");
      out.write("                checkbox.checked = false;\r\n");
      out.write("            });\r\n");
      out.write("            document.getElementById('filtroCategorias').submit();\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
